# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import state_pb2 as state__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in state_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CortexStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Focus = channel.unary_unary(
                '/slate.Cortex/Focus',
                request_serializer=state__pb2.FocusRequest.SerializeToString,
                response_deserializer=state__pb2.FocusResponse.FromString,
                _registered_method=True)
        self.Drift = channel.unary_unary(
                '/slate.Cortex/Drift',
                request_serializer=state__pb2.DriftRequest.SerializeToString,
                response_deserializer=state__pb2.DriftResponse.FromString,
                _registered_method=True)
        self.Commit = channel.unary_unary(
                '/slate.Cortex/Commit',
                request_serializer=state__pb2.Trace.SerializeToString,
                response_deserializer=state__pb2.Ack.FromString,
                _registered_method=True)
        self.Reminisce = channel.unary_unary(
                '/slate.Cortex/Reminisce',
                request_serializer=state__pb2.RecallRequest.SerializeToString,
                response_deserializer=state__pb2.RecallResponse.FromString,
                _registered_method=True)
        self.Consult = channel.unary_unary(
                '/slate.Cortex/Consult',
                request_serializer=state__pb2.QueryRequest.SerializeToString,
                response_deserializer=state__pb2.KnowledgeResponse.FromString,
                _registered_method=True)
        self.Trigger = channel.unary_unary(
                '/slate.Cortex/Trigger',
                request_serializer=state__pb2.ReflexRequest.SerializeToString,
                response_deserializer=state__pb2.ExecutionResult.FromString,
                _registered_method=True)
        self.SetVariable = channel.unary_unary(
                '/slate.Cortex/SetVariable',
                request_serializer=state__pb2.SetVariableRequest.SerializeToString,
                response_deserializer=state__pb2.Ack.FromString,
                _registered_method=True)
        self.GetVariable = channel.unary_unary(
                '/slate.Cortex/GetVariable',
                request_serializer=state__pb2.GetVariableRequest.SerializeToString,
                response_deserializer=state__pb2.VariableResponse.FromString,
                _registered_method=True)
        self.ListVariables = channel.unary_unary(
                '/slate.Cortex/ListVariables',
                request_serializer=state__pb2.ListVariablesRequest.SerializeToString,
                response_deserializer=state__pb2.ListVariablesResponse.FromString,
                _registered_method=True)
        self.DeleteVariable = channel.unary_unary(
                '/slate.Cortex/DeleteVariable',
                request_serializer=state__pb2.DeleteVariableRequest.SerializeToString,
                response_deserializer=state__pb2.Ack.FromString,
                _registered_method=True)
        self.DefineConcept = channel.unary_unary(
                '/slate.Cortex/DefineConcept',
                request_serializer=state__pb2.DefineConceptRequest.SerializeToString,
                response_deserializer=state__pb2.Ack.FromString,
                _registered_method=True)
        self.ListConcepts = channel.unary_unary(
                '/slate.Cortex/ListConcepts',
                request_serializer=state__pb2.ListConceptsRequest.SerializeToString,
                response_deserializer=state__pb2.ListConceptsResponse.FromString,
                _registered_method=True)
        self.AddGoal = channel.unary_unary(
                '/slate.Cortex/AddGoal',
                request_serializer=state__pb2.AddGoalRequest.SerializeToString,
                response_deserializer=state__pb2.GoalResponse.FromString,
                _registered_method=True)
        self.UpdateGoal = channel.unary_unary(
                '/slate.Cortex/UpdateGoal',
                request_serializer=state__pb2.UpdateGoalRequest.SerializeToString,
                response_deserializer=state__pb2.Ack.FromString,
                _registered_method=True)
        self.ListGoals = channel.unary_unary(
                '/slate.Cortex/ListGoals',
                request_serializer=state__pb2.ListGoalsRequest.SerializeToString,
                response_deserializer=state__pb2.ListGoalsResponse.FromString,
                _registered_method=True)
        self.SubmitAction = channel.unary_unary(
                '/slate.Cortex/SubmitAction',
                request_serializer=state__pb2.ActionRequest.SerializeToString,
                response_deserializer=state__pb2.ActionResponse.FromString,
                _registered_method=True)
        self.GetActionLog = channel.unary_unary(
                '/slate.Cortex/GetActionLog',
                request_serializer=state__pb2.ActionLogRequest.SerializeToString,
                response_deserializer=state__pb2.ActionLogResponse.FromString,
                _registered_method=True)
        self.RunCycle = channel.unary_unary(
                '/slate.Cortex/RunCycle',
                request_serializer=state__pb2.RunCycleRequest.SerializeToString,
                response_deserializer=state__pb2.CycleResponse.FromString,
                _registered_method=True)
        self.GetCycleHistory = channel.unary_unary(
                '/slate.Cortex/GetCycleHistory',
                request_serializer=state__pb2.CycleHistoryRequest.SerializeToString,
                response_deserializer=state__pb2.CycleHistoryResponse.FromString,
                _registered_method=True)
        self.DeleteRun = channel.unary_unary(
                '/slate.Cortex/DeleteRun',
                request_serializer=state__pb2.RunRequest.SerializeToString,
                response_deserializer=state__pb2.Ack.FromString,
                _registered_method=True)


class CortexServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Focus(self, request, context):
        """Flux (Legacy Working Memory)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Drift(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Commit(self, request, context):
        """Echoes (Episodic Memory)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reminisce(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Consult(self, request, context):
        """Nexus (Semantic Memory)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Trigger(self, request, context):
        """Reflex (Procedural Memory)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetVariable(self, request, context):
        """Working Memory (Structured Variables)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVariable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListVariables(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteVariable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DefineConcept(self, request, context):
        """Concepts (Level 4 Agency)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListConcepts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddGoal(self, request, context):
        """Goals
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateGoal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListGoals(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitAction(self, request, context):
        """Actions
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetActionLog(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunCycle(self, request, context):
        """Decision Cycle
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCycleHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteRun(self, request, context):
        """Management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CortexServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Focus': grpc.unary_unary_rpc_method_handler(
                    servicer.Focus,
                    request_deserializer=state__pb2.FocusRequest.FromString,
                    response_serializer=state__pb2.FocusResponse.SerializeToString,
            ),
            'Drift': grpc.unary_unary_rpc_method_handler(
                    servicer.Drift,
                    request_deserializer=state__pb2.DriftRequest.FromString,
                    response_serializer=state__pb2.DriftResponse.SerializeToString,
            ),
            'Commit': grpc.unary_unary_rpc_method_handler(
                    servicer.Commit,
                    request_deserializer=state__pb2.Trace.FromString,
                    response_serializer=state__pb2.Ack.SerializeToString,
            ),
            'Reminisce': grpc.unary_unary_rpc_method_handler(
                    servicer.Reminisce,
                    request_deserializer=state__pb2.RecallRequest.FromString,
                    response_serializer=state__pb2.RecallResponse.SerializeToString,
            ),
            'Consult': grpc.unary_unary_rpc_method_handler(
                    servicer.Consult,
                    request_deserializer=state__pb2.QueryRequest.FromString,
                    response_serializer=state__pb2.KnowledgeResponse.SerializeToString,
            ),
            'Trigger': grpc.unary_unary_rpc_method_handler(
                    servicer.Trigger,
                    request_deserializer=state__pb2.ReflexRequest.FromString,
                    response_serializer=state__pb2.ExecutionResult.SerializeToString,
            ),
            'SetVariable': grpc.unary_unary_rpc_method_handler(
                    servicer.SetVariable,
                    request_deserializer=state__pb2.SetVariableRequest.FromString,
                    response_serializer=state__pb2.Ack.SerializeToString,
            ),
            'GetVariable': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVariable,
                    request_deserializer=state__pb2.GetVariableRequest.FromString,
                    response_serializer=state__pb2.VariableResponse.SerializeToString,
            ),
            'ListVariables': grpc.unary_unary_rpc_method_handler(
                    servicer.ListVariables,
                    request_deserializer=state__pb2.ListVariablesRequest.FromString,
                    response_serializer=state__pb2.ListVariablesResponse.SerializeToString,
            ),
            'DeleteVariable': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteVariable,
                    request_deserializer=state__pb2.DeleteVariableRequest.FromString,
                    response_serializer=state__pb2.Ack.SerializeToString,
            ),
            'DefineConcept': grpc.unary_unary_rpc_method_handler(
                    servicer.DefineConcept,
                    request_deserializer=state__pb2.DefineConceptRequest.FromString,
                    response_serializer=state__pb2.Ack.SerializeToString,
            ),
            'ListConcepts': grpc.unary_unary_rpc_method_handler(
                    servicer.ListConcepts,
                    request_deserializer=state__pb2.ListConceptsRequest.FromString,
                    response_serializer=state__pb2.ListConceptsResponse.SerializeToString,
            ),
            'AddGoal': grpc.unary_unary_rpc_method_handler(
                    servicer.AddGoal,
                    request_deserializer=state__pb2.AddGoalRequest.FromString,
                    response_serializer=state__pb2.GoalResponse.SerializeToString,
            ),
            'UpdateGoal': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateGoal,
                    request_deserializer=state__pb2.UpdateGoalRequest.FromString,
                    response_serializer=state__pb2.Ack.SerializeToString,
            ),
            'ListGoals': grpc.unary_unary_rpc_method_handler(
                    servicer.ListGoals,
                    request_deserializer=state__pb2.ListGoalsRequest.FromString,
                    response_serializer=state__pb2.ListGoalsResponse.SerializeToString,
            ),
            'SubmitAction': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitAction,
                    request_deserializer=state__pb2.ActionRequest.FromString,
                    response_serializer=state__pb2.ActionResponse.SerializeToString,
            ),
            'GetActionLog': grpc.unary_unary_rpc_method_handler(
                    servicer.GetActionLog,
                    request_deserializer=state__pb2.ActionLogRequest.FromString,
                    response_serializer=state__pb2.ActionLogResponse.SerializeToString,
            ),
            'RunCycle': grpc.unary_unary_rpc_method_handler(
                    servicer.RunCycle,
                    request_deserializer=state__pb2.RunCycleRequest.FromString,
                    response_serializer=state__pb2.CycleResponse.SerializeToString,
            ),
            'GetCycleHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCycleHistory,
                    request_deserializer=state__pb2.CycleHistoryRequest.FromString,
                    response_serializer=state__pb2.CycleHistoryResponse.SerializeToString,
            ),
            'DeleteRun': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteRun,
                    request_deserializer=state__pb2.RunRequest.FromString,
                    response_serializer=state__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'slate.Cortex', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('slate.Cortex', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Cortex(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Focus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/slate.Cortex/Focus',
            state__pb2.FocusRequest.SerializeToString,
            state__pb2.FocusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Drift(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/slate.Cortex/Drift',
            state__pb2.DriftRequest.SerializeToString,
            state__pb2.DriftResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Commit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/slate.Cortex/Commit',
            state__pb2.Trace.SerializeToString,
            state__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Reminisce(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/slate.Cortex/Reminisce',
            state__pb2.RecallRequest.SerializeToString,
            state__pb2.RecallResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Consult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/slate.Cortex/Consult',
            state__pb2.QueryRequest.SerializeToString,
            state__pb2.KnowledgeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Trigger(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/slate.Cortex/Trigger',
            state__pb2.ReflexRequest.SerializeToString,
            state__pb2.ExecutionResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetVariable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/slate.Cortex/SetVariable',
            state__pb2.SetVariableRequest.SerializeToString,
            state__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVariable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/slate.Cortex/GetVariable',
            state__pb2.GetVariableRequest.SerializeToString,
            state__pb2.VariableResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListVariables(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/slate.Cortex/ListVariables',
            state__pb2.ListVariablesRequest.SerializeToString,
            state__pb2.ListVariablesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteVariable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/slate.Cortex/DeleteVariable',
            state__pb2.DeleteVariableRequest.SerializeToString,
            state__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DefineConcept(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/slate.Cortex/DefineConcept',
            state__pb2.DefineConceptRequest.SerializeToString,
            state__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListConcepts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/slate.Cortex/ListConcepts',
            state__pb2.ListConceptsRequest.SerializeToString,
            state__pb2.ListConceptsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddGoal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/slate.Cortex/AddGoal',
            state__pb2.AddGoalRequest.SerializeToString,
            state__pb2.GoalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateGoal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/slate.Cortex/UpdateGoal',
            state__pb2.UpdateGoalRequest.SerializeToString,
            state__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListGoals(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/slate.Cortex/ListGoals',
            state__pb2.ListGoalsRequest.SerializeToString,
            state__pb2.ListGoalsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/slate.Cortex/SubmitAction',
            state__pb2.ActionRequest.SerializeToString,
            state__pb2.ActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetActionLog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/slate.Cortex/GetActionLog',
            state__pb2.ActionLogRequest.SerializeToString,
            state__pb2.ActionLogResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunCycle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/slate.Cortex/RunCycle',
            state__pb2.RunCycleRequest.SerializeToString,
            state__pb2.CycleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCycleHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/slate.Cortex/GetCycleHistory',
            state__pb2.CycleHistoryRequest.SerializeToString,
            state__pb2.CycleHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/slate.Cortex/DeleteRun',
            state__pb2.RunRequest.SerializeToString,
            state__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
