# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import ricedb_pb2 as ricedb__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ricedb_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RiceDBStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Login = channel.unary_unary(
                '/ricedb.RiceDB/Login',
                request_serializer=ricedb__pb2.LoginRequest.SerializeToString,
                response_deserializer=ricedb__pb2.LoginResponse.FromString,
                _registered_method=True)
        self.CreateUser = channel.unary_unary(
                '/ricedb.RiceDB/CreateUser',
                request_serializer=ricedb__pb2.CreateUserRequest.SerializeToString,
                response_deserializer=ricedb__pb2.CreateUserResponse.FromString,
                _registered_method=True)
        self.DeleteUser = channel.unary_unary(
                '/ricedb.RiceDB/DeleteUser',
                request_serializer=ricedb__pb2.DeleteUserRequest.SerializeToString,
                response_deserializer=ricedb__pb2.DeleteUserResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/ricedb.RiceDB/Health',
                request_serializer=ricedb__pb2.HealthRequest.SerializeToString,
                response_deserializer=ricedb__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.Insert = channel.unary_unary(
                '/ricedb.RiceDB/Insert',
                request_serializer=ricedb__pb2.InsertRequest.SerializeToString,
                response_deserializer=ricedb__pb2.InsertResponse.FromString,
                _registered_method=True)
        self.GetNode = channel.unary_unary(
                '/ricedb.RiceDB/GetNode',
                request_serializer=ricedb__pb2.GetNodeRequest.SerializeToString,
                response_deserializer=ricedb__pb2.GetNodeResponse.FromString,
                _registered_method=True)
        self.DeleteNode = channel.unary_unary(
                '/ricedb.RiceDB/DeleteNode',
                request_serializer=ricedb__pb2.DeleteNodeRequest.SerializeToString,
                response_deserializer=ricedb__pb2.DeleteNodeResponse.FromString,
                _registered_method=True)
        self.Search = channel.unary_unary(
                '/ricedb.RiceDB/Search',
                request_serializer=ricedb__pb2.SearchRequest.SerializeToString,
                response_deserializer=ricedb__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.BatchInsert = channel.stream_unary(
                '/ricedb.RiceDB/BatchInsert',
                request_serializer=ricedb__pb2.InsertRequest.SerializeToString,
                response_deserializer=ricedb__pb2.BatchInsertResponse.FromString,
                _registered_method=True)
        self.CreateSession = channel.unary_unary(
                '/ricedb.RiceDB/CreateSession',
                request_serializer=ricedb__pb2.CreateSessionRequest.SerializeToString,
                response_deserializer=ricedb__pb2.CreateSessionResponse.FromString,
                _registered_method=True)
        self.SnapshotSession = channel.unary_unary(
                '/ricedb.RiceDB/SnapshotSession',
                request_serializer=ricedb__pb2.SnapshotSessionRequest.SerializeToString,
                response_deserializer=ricedb__pb2.SnapshotSessionResponse.FromString,
                _registered_method=True)
        self.LoadSession = channel.unary_unary(
                '/ricedb.RiceDB/LoadSession',
                request_serializer=ricedb__pb2.LoadSessionRequest.SerializeToString,
                response_deserializer=ricedb__pb2.LoadSessionResponse.FromString,
                _registered_method=True)
        self.CommitSession = channel.unary_unary(
                '/ricedb.RiceDB/CommitSession',
                request_serializer=ricedb__pb2.CommitSessionRequest.SerializeToString,
                response_deserializer=ricedb__pb2.CommitSessionResponse.FromString,
                _registered_method=True)
        self.DropSession = channel.unary_unary(
                '/ricedb.RiceDB/DropSession',
                request_serializer=ricedb__pb2.DropSessionRequest.SerializeToString,
                response_deserializer=ricedb__pb2.DropSessionResponse.FromString,
                _registered_method=True)


class RiceDBServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Insert(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchInsert(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SnapshotSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommitSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DropSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RiceDBServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=ricedb__pb2.LoginRequest.FromString,
                    response_serializer=ricedb__pb2.LoginResponse.SerializeToString,
            ),
            'CreateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUser,
                    request_deserializer=ricedb__pb2.CreateUserRequest.FromString,
                    response_serializer=ricedb__pb2.CreateUserResponse.SerializeToString,
            ),
            'DeleteUser': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteUser,
                    request_deserializer=ricedb__pb2.DeleteUserRequest.FromString,
                    response_serializer=ricedb__pb2.DeleteUserResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=ricedb__pb2.HealthRequest.FromString,
                    response_serializer=ricedb__pb2.HealthResponse.SerializeToString,
            ),
            'Insert': grpc.unary_unary_rpc_method_handler(
                    servicer.Insert,
                    request_deserializer=ricedb__pb2.InsertRequest.FromString,
                    response_serializer=ricedb__pb2.InsertResponse.SerializeToString,
            ),
            'GetNode': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNode,
                    request_deserializer=ricedb__pb2.GetNodeRequest.FromString,
                    response_serializer=ricedb__pb2.GetNodeResponse.SerializeToString,
            ),
            'DeleteNode': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteNode,
                    request_deserializer=ricedb__pb2.DeleteNodeRequest.FromString,
                    response_serializer=ricedb__pb2.DeleteNodeResponse.SerializeToString,
            ),
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=ricedb__pb2.SearchRequest.FromString,
                    response_serializer=ricedb__pb2.SearchResponse.SerializeToString,
            ),
            'BatchInsert': grpc.stream_unary_rpc_method_handler(
                    servicer.BatchInsert,
                    request_deserializer=ricedb__pb2.InsertRequest.FromString,
                    response_serializer=ricedb__pb2.BatchInsertResponse.SerializeToString,
            ),
            'CreateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSession,
                    request_deserializer=ricedb__pb2.CreateSessionRequest.FromString,
                    response_serializer=ricedb__pb2.CreateSessionResponse.SerializeToString,
            ),
            'SnapshotSession': grpc.unary_unary_rpc_method_handler(
                    servicer.SnapshotSession,
                    request_deserializer=ricedb__pb2.SnapshotSessionRequest.FromString,
                    response_serializer=ricedb__pb2.SnapshotSessionResponse.SerializeToString,
            ),
            'LoadSession': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadSession,
                    request_deserializer=ricedb__pb2.LoadSessionRequest.FromString,
                    response_serializer=ricedb__pb2.LoadSessionResponse.SerializeToString,
            ),
            'CommitSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CommitSession,
                    request_deserializer=ricedb__pb2.CommitSessionRequest.FromString,
                    response_serializer=ricedb__pb2.CommitSessionResponse.SerializeToString,
            ),
            'DropSession': grpc.unary_unary_rpc_method_handler(
                    servicer.DropSession,
                    request_deserializer=ricedb__pb2.DropSessionRequest.FromString,
                    response_serializer=ricedb__pb2.DropSessionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ricedb.RiceDB', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ricedb.RiceDB', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RiceDB(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ricedb.RiceDB/Login',
            ricedb__pb2.LoginRequest.SerializeToString,
            ricedb__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ricedb.RiceDB/CreateUser',
            ricedb__pb2.CreateUserRequest.SerializeToString,
            ricedb__pb2.CreateUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ricedb.RiceDB/DeleteUser',
            ricedb__pb2.DeleteUserRequest.SerializeToString,
            ricedb__pb2.DeleteUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ricedb.RiceDB/Health',
            ricedb__pb2.HealthRequest.SerializeToString,
            ricedb__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Insert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ricedb.RiceDB/Insert',
            ricedb__pb2.InsertRequest.SerializeToString,
            ricedb__pb2.InsertResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ricedb.RiceDB/GetNode',
            ricedb__pb2.GetNodeRequest.SerializeToString,
            ricedb__pb2.GetNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ricedb.RiceDB/DeleteNode',
            ricedb__pb2.DeleteNodeRequest.SerializeToString,
            ricedb__pb2.DeleteNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ricedb.RiceDB/Search',
            ricedb__pb2.SearchRequest.SerializeToString,
            ricedb__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchInsert(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/ricedb.RiceDB/BatchInsert',
            ricedb__pb2.InsertRequest.SerializeToString,
            ricedb__pb2.BatchInsertResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ricedb.RiceDB/CreateSession',
            ricedb__pb2.CreateSessionRequest.SerializeToString,
            ricedb__pb2.CreateSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SnapshotSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ricedb.RiceDB/SnapshotSession',
            ricedb__pb2.SnapshotSessionRequest.SerializeToString,
            ricedb__pb2.SnapshotSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ricedb.RiceDB/LoadSession',
            ricedb__pb2.LoadSessionRequest.SerializeToString,
            ricedb__pb2.LoadSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CommitSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ricedb.RiceDB/CommitSession',
            ricedb__pb2.CommitSessionRequest.SerializeToString,
            ricedb__pb2.CommitSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DropSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ricedb.RiceDB/DropSession',
            ricedb__pb2.DropSessionRequest.SerializeToString,
            ricedb__pb2.DropSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
